name: Main branch

# TODO: Temporary solution. Remove it once migration to Lerna is completed 
defaults:
  run:
    working-directory: dashboard

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "CODEOWNERS"
      - "README.md"
    branches:
      - main
      - "release-*"

jobs:
  build-push:
    name: Build and push application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_REPOSITORY: "ghcr.io/capactio"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build application
        # Unfortunately, the only way to not treat warnings as errors
        # on CI is setting `CI` env to `false`.
        # See the issue https://github.com/facebook/create-react-app/issues/3657
        run: CI=false npm run build

      - name: Set Docker tag env
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: npm run docker:build-image

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: npm run docker:push-image
